"""Step 2: Test Flow on user stories that map to a concrete iTrust2 page.

For each mapped user story, take the Gherkin generated by AutoUAT
(outputs/autouat/<slug>.feature), capture the real rendered HTML of the
mapped page from the running app, and generate a Cypress script.
Saves outputs/autouat/<slug>.spec.ts.

Paper grounding: Test Flow inputs = user story + Gherkin scenarios + HTML of
the pages under test by URL (Sections II-D, III-B).

Usage:
    python scripts/run_step2_testflow.py            # all mapped stories
    python scripts/run_step2_testflow.py add-hospital delete-user  # subset
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from atg.itrust2 import fetch_page_html_authenticated
from atg.models import TestFlowInput, UserStory
from atg.testflow import TestFlow
from atg.url_fill import fill_page_url
from scripts.run_all_user_stories import parse_user_stories
from scripts.uc_map import uc_by_slug

OUT = Path(__file__).resolve().parent.parent / "outputs" / "autouat"
BASE = "http://localhost:8080/iTrust2"
SAMPLE_PASSWORD = "123456"  # iTrust2 documented sample users

# Cac custom command CO THAT trong cypress/support/commands.ts. Prompt phai noi
# dung danh sach nay, neu khong model se tu bia ra ham khong ton tai.
PREDEFINED_COMMANDS = "\n".join(
    [
        "// Custom commands co san trong cypress/support/commands.ts (KHONG duoc bia them)",
        'cy.login(username: string, password?: string)   // dang nhap that, password mac dinh "123456"',
        "cy.loginAsAdmin()",
        "cy.loginAsHCP()",
        "cy.loginAsPatient()",
        "cy.loginAsRegisteredPatient()",
        "cy.logout()",
        "",
        '// Tai khoan mau cua iTrust2 (password deu la "123456"): admin, hcp, patient, er, lt',
    ]
)

# slug -> (relative page URL, login username)
# Stories with no single UI page (system/logic-level) are intentionally omitted
# (e.g. session-timeout, ban, log-all-events, email-alerts, reset-password).
MAP: dict[str, tuple[str, str]] = {
    "add-user": ("admin/users", "admin"),
    "delete-user": ("admin/users", "admin"),
    "lockout-after-failed-attempts": ("login", "admin"),
    "patient-edits-own-demographics": ("patient/editDemographics", "patient"),
    "hcp-edits-patient-demographics": ("hcp/editPatientDemographics", "hcp"),
    "hcp-er-lab-tech-edits-own-demographics": ("personnel/editDemographics", "hcp"),
    "add-hospital": ("admin/hospitals", "admin"),
    "delete-hospital": ("admin/hospitals", "admin"),
    "request-appointment": ("patient/manageAppointmentRequest", "patient"),
    "view-delete-appointment-requests": ("patient/manageAppointmentRequest", "patient"),
    "approve-decline-requests": ("hcp/appointmentRequests", "hcp"),
    "view-upcoming-appointments": ("hcp/appointmentRequests", "hcp"),
    "view-office-visit": ("patient/index", "patient"),
    "document-office-visit": ("hcp/documentOfficeVisit", "hcp"),
    "enter-health-metrics": ("hcp/documentOfficeVisit", "hcp"),
    "view-health-metrics": ("patient/index", "patient"),
    "add-prescription": ("hcp/documentOfficeVisit", "hcp"),
    "view-prescriptions": ("patient/officeVisit/viewPrescriptions", "patient"),
    "manage-ndc-drugs": ("admin/drugs", "admin"),
    "record-diagnosis": ("hcp/documentOfficeVisit", "hcp"),
    "view-diagnoses": ("patient/officeVisit/viewDiagnoses", "patient"),
    "manage-icd-10-codes": ("admin/manageICDCodes", "admin"),
    "hcp-edits-patient-demographics-via-edit-patient": ("hcp/editPatientDemographics", "hcp"),
    "warning-on-switching-patient": ("hcp/editPatientDemographics", "hcp"),
    # Access log is shown as a fragment on the landing page (no standalone /logView).
    "view-access-log": ("admin/index", "admin"),
    "log-all-events": ("admin/index", "admin"),
    # Email alerts are listed on the /viewEmails page.
    "email-alerts": ("viewEmails", "admin"),
    # System-level / auth stories mapped to their *closest* real page.
    "login": ("login", "admin"),
    "recent-events-on-landing": ("admin/index", "admin"),
    "change-password": ("admin/users", "admin"),
    "reset-password": ("login", "admin"),
    "session-timeout": ("login", "admin"),
    "ban-after-repeated-lockouts": ("login", "admin"),
}


def _title_from_feature(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    for line in text.splitlines():
        if line.strip().lower().startswith("feature:"):
            return line.split(":", 1)[1].strip()
    return path.stem


_STORY_MD = Path(__file__).resolve().parent.parent / "user_stories.md"
_STORIES: dict[str, tuple[str, str]] | None = None


def _all_stories() -> dict[str, tuple[str, str]]:
    """{slug: (title, description)} doc tu user_stories.md."""
    global _STORIES
    if _STORIES is None:
        _STORIES = {}
        for title, desc in parse_user_stories(_STORY_MD.read_text(encoding="utf-8")):
            slug = re.sub(r"[^A-Za-z0-9]+", "-", title).strip("-").lower()
            _STORIES[slug] = (title, desc)
    return _STORIES


def _story_for(slug: str, gherkin_path: Path) -> tuple[str, str]:
    """User story (title, description) day du - input context cua Test Flow."""
    story = _all_stories().get(slug)
    if story:
        return story
    title = _title_from_feature(gherkin_path)
    return title, title


def run_one(slug: str, rel_url: str, user: str) -> None:
    uc = uc_by_slug().get(slug, "")
    gherkin_path = (OUT / uc / f"{slug}.feature") if uc else (OUT / f"{slug}.feature")
    if not gherkin_path.exists():
        gherkin_path = OUT / f"{slug}.feature"  # fallback: flat layout
    if not gherkin_path.exists():
        print(f"[SKIP] {slug}: no AutoUAT output found")
        return
    gherkin = gherkin_path.read_text(encoding="utf-8")
    # Paper Table: Test Flow takes the whole user story (title + description),
    # not only the feature title, as context.
    title, description = _story_for(slug, gherkin_path)
    user_story = UserStory(title=title, description=description)

    page_url = f"{BASE}/{rel_url}"
    html = fetch_page_html_authenticated(page_url, username=user, password=SAMPLE_PASSWORD)

    res = TestFlow().generate(
        TestFlowInput(
            user_story=user_story,
            gherkin_scenarios=gherkin,
            html=html,
            product_context="iTrust2 EHR web app (Spring Boot + AngularJS).",
            page_urls=[rel_url],
            predefined_commands=PREDEFINED_COMMANDS,
        )
    )
    # Paper Listing 4: the URL of the page under test is filled into the script.
    script, replaced = fill_page_url(res.script, rel_url)
    out_path = (OUT / uc / f"{slug}.spec.ts") if uc else (OUT / f"{slug}.spec.ts")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(script, encoding="utf-8")
    print(
        f"[OK] {slug}: {gherkin.count('Scenario:')} scenarios, "
        f"html {len(html)} chars, url filled {replaced}x"
    )


def main() -> int:
    wanted = sys.argv[1:] or list(MAP)
    ok = 0
    for slug in wanted:
        if slug not in MAP:
            print(f"[SKIP] unknown slug: {slug}")
            continue
        rel_url, user = MAP[slug]
        try:
            run_one(slug, rel_url, user)
            ok += 1
        except Exception as exc:  # noqa: BLE001
            print(f"[FAIL] {slug}: {type(exc).__name__}: {exc}")
    print(f"\nDone: {ok} stories -> Cypress in {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
